module.exports = {
    id: Number, 
    title: String,
    frame: String,
    description: String,
    driveTrain: String,
    fork: String,
    shock: String,
    brakes: String,
    rims: String,
    hubs: String,
    tires: String,
    spokes: String,
    crank: String,
    frontDerailleur: String,
    rearDerailleur: String,
    rearCogs: String,
    pedals: String,
    shifters: String,
    handlebar: String,
    stem: String,
    headset: String,
    brakeLevers: String,
    saddle: String,
    seatpost: String,
    image: String,
    
    frameMaterial: String,
    travel: Number,
    RRP: String, 
    type: String, 
    brand: String, 
    createdAt: Date, 
    updatedAt: Date
}